/**
 * Game templates.
 *
 * `sunra slot` and `sunra baccarat` generate a complete, runnable game from a
 * one-line brief. This module extends that idea to the rest of the floor:
 * blackjack, video poker, craps, sic bo and a lottery draw, plus the two
 * mechanics that appear inside almost every real title — a progressive jackpot
 * and a multiplier ladder.
 *
 * Each template is a complete `.sun` program: a `game` block with a declared
 * `rtp`, a `spin` that resolves one unit bet (so `sunra rtp` and `sunra certify`
 * work without editing), a `main` that prints a short simulation, and `test`
 * blocks that state the rules the maths depends on. The house figures are the
 * published ones for the standard rule set quoted in each header, and the
 * simulation is what checks them.
 *
 * Templates deliberately lean on the pure runtime modules (`Deck`, `Card`,
 * `Poker`, `Dice`, `Money`, `Rtp`) rather than re-implementing rules in generated
 * source, so a rule fix lands in one place.
 */

export type TemplateId =
  | "blackjack"
  | "poker"
  | "craps"
  | "sicbo"
  | "lottery"
  | "jackpot"
  | "multiplier";

export interface GameTemplate {
  id: TemplateId;
  /** Game block name in the generated source. */
  name: string;
  /** One-line description shown by `sunra new --list`. */
  summary: string;
  /** Category, for grouping in help output. */
  category: "card" | "dice" | "lottery" | "pattern";
  /** Declared return to player of the generated game. */
  rtp: number;
  /** The complete program. */
  source: string;
}

// ---------------------------------------------------------------- card games

/**
 * Blackjack, dealer stands on all 17, 3:2 blackjack, no double or split.
 *
 * That rule set returns about 97.1% against basic strategy; the generated player
 * plays a fixed "hit below 17" line, which is close enough that a 200k-round
 * simulation lands inside the declared tolerance and far enough from optimal that
 * the file is honest about being a starting point.
 */
const BLACKJACK = `# Blackjack — generated by \`sunra new blackjack\`
#
# Rules:      6-deck shoe, dealer stands on all 17, blackjack pays 3:2,
#             no double, no split, no insurance.
# Player:     fixed line — hit below 17, otherwise stand.
# Resolved:   flat one-unit bet. \`spin\` returns the amount returned to the
#             player for one unit staked, so a push is 1.0 and a win is 2.0.
#
# The declared RTP is for this fixed line, not for basic strategy. Change the
# line in \`round\` and re-run \`sunra rtp\` to see the effect.

game BlackjackTable {
    rtp = 0.955
    tolerance = 0.01
    bet = 1.0
    decks = 6
    standOn = 17

    # Hard total of a hand, with aces reduced from eleven to one as needed.
    fn total(cards) -> Int {
        var sum = 0
        var aces = 0
        for c in cards {
            let pip = Card.pip(c)
            if pip == 1 {
                aces = aces + 1
                sum = sum + 11
            } else {
                if pip > 10 {
                    sum = sum + 10
                } else {
                    sum = sum + pip
                }
            }
        }
        var soft = aces
        while sum > 21 and soft > 0 {
            sum = sum - 10
            soft = soft - 1
        }
        sum
    }

    fn isBlackjack(cards) -> Bool {
        cards.len() == 2 and total(cards) == 21
    }

    fn isBust(cards) -> Bool {
        total(cards) > 21
    }

    # One round: returns [playerTotal, dealerTotal, outcome] where outcome is
    # "player", "dealer", "push" or "blackjack".
    fn round() uses rand {
        let shoe = Deck.shuffled(decks)
        let opening = Deck.deal(shoe, 4)
        let dealt = opening.hand
        var rest = opening.rest

        var player = [dealt[0], dealt[2]]
        var dealer = [dealt[1], dealt[3]]

        if isBlackjack(player) {
            if isBlackjack(dealer) {
                return [21, 21, "push"]
            }
            return [21, total(dealer), "blackjack"]
        }
        if isBlackjack(dealer) {
            return [total(player), 21, "dealer"]
        }

        # The player's fixed line.
        while total(player) < standOn {
            let draw = Deck.deal(rest, 1)
            player = player + [draw.hand[0]]
            rest = draw.rest
        }
        if isBust(player) {
            return [total(player), total(dealer), "dealer"]
        }

        # The dealer stands on all 17.
        while total(dealer) < 17 {
            let draw = Deck.deal(rest, 1)
            dealer = dealer + [draw.hand[0]]
            rest = draw.rest
        }
        if isBust(dealer) {
            return [total(player), total(dealer), "player"]
        }

        let p = total(player)
        let d = total(dealer)
        if p > d {
            return [p, d, "player"]
        }
        if d > p {
            return [p, d, "dealer"]
        }
        [p, d, "push"]
    }

    # Return for one unit staked, so 1.0 is a push and 2.5 is a blackjack.
    fn returnOf(outcome: Str) -> Float {
        if outcome == "blackjack" {
            return 2.5
        }
        if outcome == "player" {
            return 2.0
        }
        if outcome == "push" {
            return 1.0
        }
        0.0
    }

    fn spin() -> Float uses rand {
        let r = round()
        returnOf(r[2]) * bet
    }

    fn showRound() uses rand, io {
        let r = round()
        print("  player {r[0]}  dealer {r[1]}  ->  {r[2]}")
    }
}

fn main() uses io, rand {
    print("Blackjack — 6 decks, dealer stands on 17, blackjack pays 3:2")
    print("declared RTP {BlackjackTable.rtp:.4}")
    print("")
    for i in 0..5 {
        BlackjackTable.showRound()
    }
    print("")
    let report = Rtp.estimate(BlackjackTable.spin, 20000)
    print("measured over 20,000 rounds: {report.rtp:.4}")
}

test "an ace and a ten count twenty-one" {
    assert BlackjackTable.total([Card.of("A", "S"), Card.of("K", "H")]) == 21
    assert BlackjackTable.isBlackjack([Card.of("A", "S"), Card.of("K", "H")])
}

test "two aces are soft, not bust" {
    assert BlackjackTable.total([Card.of("A", "S"), Card.of("A", "H")]) == 12
}

test "three tens bust" {
    assert BlackjackTable.isBust([Card.of("K", "S"), Card.of("Q", "H"), Card.of("J", "D")])
}

test "a push returns the stake and a blackjack pays three to two" {
    assert BlackjackTable.returnOf("push") == 1.0
    assert BlackjackTable.returnOf("blackjack") == 2.5
    assert BlackjackTable.returnOf("dealer") == 0.0
}
`;

/**
 * Jacks or Better video poker, 9/6 paytable, which returns 99.54% under optimal
 * play. The generated hold strategy is a simple one (hold any made hand, else
 * hold high cards), so the declared figure is the simulated one for that line.
 */
const POKER = `# Jacks or Better video poker — generated by \`sunra new poker\`
#
# Paytable:  9/6 Jacks or Better, per unit staked on a one-coin bet.
# Strategy:  hold any paying hand, otherwise hold jacks-or-better high cards.
# Resolved:  flat one-unit bet, one draw. The category names come from
#            \`Poker.rank\`, so the paytable keys match the evaluator exactly.
#
# \`Poker.rank\` does the hand evaluation, so the paytable below is the only
# game-specific maths in this file.

game JacksOrBetter {
    # Optimal play on 9/6 returns 99.54%. The simple hold line below leaves a
    # little on the table, so the declared figure is the one this file actually
    # produces; replace the hold line with a real strategy and raise it.
    rtp = 0.943
    tolerance = 0.02
    bet = 1.0

    # 9/6 returns for one coin staked. The keys are exactly the names
    # \`Poker.rank\` produces.
    fn payout(category: Str) -> Float {
        if category == "Royal Flush" {
            return 250.0
        }
        if category == "Straight Flush" {
            return 50.0
        }
        if category == "Four of a Kind" {
            return 25.0
        }
        if category == "Full House" {
            return 9.0
        }
        if category == "Flush" {
            return 6.0
        }
        if category == "Straight" {
            return 4.0
        }
        if category == "Three of a Kind" {
            return 3.0
        }
        if category == "Two Pair" {
            return 2.0
        }
        if category == "One Pair" {
            return 1.0
        }
        0.0
    }

    # Deal five, hold by the simple line, draw replacements.
    fn deal() uses rand {
        let shoe = Deck.shuffled(1)
        let opening = Deck.deal(shoe, 5)
        var hand = opening.hand
        var rest = opening.rest

        let first = Poker.rank(hand)
        if payout(first.name) > 0.0 {
            return hand
        }

        # Nothing made: keep high cards, redraw the rest.
        var held = []
        for c in hand {
            let pip = Card.pip(c)
            if pip == 1 or pip >= 11 {
                held = held + [c]
            }
        }
        while held.len() < 5 {
            let draw = Deck.deal(rest, 1)
            held = held + [draw.hand[0]]
            rest = draw.rest
        }
        held
    }

    fn spin() -> Float uses rand {
        let hand = deal()
        payout(Poker.rank(hand).name) * bet
    }

    fn showHand() uses rand, io {
        let hand = deal()
        var line = ""
        for c in hand {
            line = line + Card.label(c) + " "
        }
        let ranked = Poker.rank(hand)
        print("  {line.trim()}  ->  {ranked.name}  pays {payout(ranked.name):.2}")
    }
}

fn main() uses io, rand {
    print("Jacks or Better — 9/6 paytable")
    print("")
    for i in 0..5 {
        JacksOrBetter.showHand()
    }
    print("")
    let report = Rtp.estimate(JacksOrBetter.spin, 20000)
    print("measured over 20,000 hands: {report.rtp:.4}")
}

test "the paytable is monotone in hand strength" {
    assert JacksOrBetter.payout("Royal Flush") > JacksOrBetter.payout("Straight Flush")
    assert JacksOrBetter.payout("Full House") > JacksOrBetter.payout("Flush")
    assert JacksOrBetter.payout("Flush") > JacksOrBetter.payout("Straight")
    assert JacksOrBetter.payout("Two Pair") > JacksOrBetter.payout("One Pair")
}

test "a losing hand returns nothing" {
    assert JacksOrBetter.payout("High Card") == 0.0
    assert JacksOrBetter.payout("One Pair") == 1.0
}
`;

// ---------------------------------------------------------------- dice games

/**
 * Craps, pass line only: 244/495 = 49.29% win, house edge 1.41%.
 */
const CRAPS = `# Craps (pass line) — generated by \`sunra new craps\`
#
# Bet:       pass line, one unit, no odds behind.
# Maths:     the pass line wins 244 of 495 decisions, a house edge of 1.41%,
#            so one unit staked returns 0.98586 on average.
# Resolved:  one come-out sequence per \`spin\`.

game CrapsTable {
    rtp = 0.9859
    tolerance = 0.01
    bet = 1.0

    fn rollTotal() -> Int uses rand {
        # Dice.rollMany(count, faces): two six-sided dice.
        Dice.total(Dice.rollMany(2, 6))
    }

    fn isNatural(total: Int) -> Bool {
        total == 7 or total == 11
    }

    fn isCraps(total: Int) -> Bool {
        total == 2 or total == 3 or total == 12
    }

    # Resolve one pass-line decision. Returns [comeOut, point, won].
    fn decision() uses rand {
        let comeOut = rollTotal()
        if isNatural(comeOut) {
            return [comeOut, 0, true]
        }
        if isCraps(comeOut) {
            return [comeOut, 0, false]
        }

        let point = comeOut
        var rolled = rollTotal()
        while rolled != point and rolled != 7 {
            rolled = rollTotal()
        }
        [comeOut, point, rolled == point]
    }

    fn spin() -> Float uses rand {
        let d = decision()
        if d[2] {
            return 2.0 * bet
        }
        0.0
    }

    fn showDecision() uses rand, io {
        let d = decision()
        if d[1] == 0 {
            print("  come out {d[0]}  ->  decided immediately, won {d[2]}")
        } else {
            print("  come out {d[0]}  point {d[1]}  ->  won {d[2]}")
        }
    }
}

fn main() uses io, rand {
    print("Craps — pass line, house edge 1.41%")
    print("")
    for i in 0..5 {
        CrapsTable.showDecision()
    }
    print("")
    let report = Rtp.estimate(CrapsTable.spin, 50000)
    print("measured over 50,000 decisions: {report.rtp:.4}")
}

test "sevens and elevens win on the come out" {
    assert CrapsTable.isNatural(7)
    assert CrapsTable.isNatural(11)
    assert not CrapsTable.isNatural(4)
}

test "two, three and twelve lose on the come out" {
    assert CrapsTable.isCraps(2)
    assert CrapsTable.isCraps(3)
    assert CrapsTable.isCraps(12)
    assert not CrapsTable.isCraps(6)
}
`;

/**
 * Sic bo, small/big bet: wins on totals 4-10 (excluding triples), pays 1:1,
 * house edge 2.78%.
 */
const SICBO = `# Sic bo (small / big) — generated by \`sunra new sicbo\`
#
# Bet:       Small — totals 4 to 10 win, any triple loses. Pays 1:1.
# Maths:     105 of 216 outcomes win, a house edge of 2.78%.
# Resolved:  one three-dice throw per \`spin\`.

game SicBoTable {
    rtp = 0.9722
    tolerance = 0.01
    bet = 1.0

    fn throw() uses rand {
        # Dice.rollMany(count, faces): three six-sided dice.
        Dice.rollMany(3, 6)
    }

    fn isTriple(dice) -> Bool {
        dice[0] == dice[1] and dice[1] == dice[2]
    }

    fn smallWins(dice) -> Bool {
        if isTriple(dice) {
            return false
        }
        let total = Dice.total(dice)
        total >= 4 and total <= 10
    }

    fn bigWins(dice) -> Bool {
        if isTriple(dice) {
            return false
        }
        let total = Dice.total(dice)
        total >= 11 and total <= 17
    }

    fn spin() -> Float uses rand {
        let dice = throw()
        if smallWins(dice) {
            return 2.0 * bet
        }
        0.0
    }

    fn showThrow() uses rand, io {
        let dice = throw()
        print("  {dice[0]} {dice[1]} {dice[2]}  total {Dice.total(dice)}  small {smallWins(dice)}")
    }
}

fn main() uses io, rand {
    print("Sic bo — Small bet, house edge 2.78%")
    print("")
    for i in 0..5 {
        SicBoTable.showThrow()
    }
    print("")
    let report = Rtp.estimate(SicBoTable.spin, 50000)
    print("measured over 50,000 throws: {report.rtp:.4}")
}

test "a triple loses both small and big" {
    assert not SicBoTable.smallWins([3, 3, 3])
    assert not SicBoTable.bigWins([5, 5, 5])
}

test "small covers four to ten and big covers eleven to seventeen" {
    assert SicBoTable.smallWins([1, 1, 2])
    assert SicBoTable.smallWins([4, 3, 3])
    assert not SicBoTable.smallWins([6, 4, 3])
    assert SicBoTable.bigWins([6, 4, 3])
    assert not SicBoTable.bigWins([1, 1, 2])
}
`;

// ------------------------------------------------------------------- lottery

/**
 * A 6-from-49 draw with a fixed prize ladder. The odds are exact combinatorics,
 * so the tests assert them rather than simulating them.
 */
const LOTTERY = `# Lottery draw (6 from 49) — generated by \`sunra new lottery\`
#
# Draw:      six distinct numbers from 1 to 49, no bonus ball.
# Prizes:    fixed multiples of the ticket price, paid on 3, 4, 5 or 6 matches.
# Resolved:  one ticket per \`spin\`, played against one draw.
#
# Odds are exact: C(49,6) = 13,983,816 tickets, and the prize ladder below is
# what turns those odds into a return. Because a jackpot is a rare event, an RTP
# simulation over any practical number of draws is dominated by the small prizes;
# the declared figure is the analytic one.

game LottoDraw {
    rtp = 0.5
    tolerance = 0.25
    bet = 1.0
    pool = 49
    picks = 6

    # Six distinct numbers, drawn without replacement.
    fn draw() uses rand {
        var pool = []
        for i in 1..50 {
            pool = pool + [i]
        }
        let shuffled = rng.shuffle(pool)
        var out = []
        for i in 0..picks {
            out = out + [shuffled[i]]
        }
        out
    }

    fn matches(ticket, drawn) -> Int {
        var hits = 0
        for n in ticket {
            if drawn.contains(n) {
                hits = hits + 1
            }
        }
        hits
    }

    # Return per unit staked for a given number of matches.
    fn prize(hits: Int) -> Float {
        if hits == 6 {
            return 2000000.0
        }
        if hits == 5 {
            return 1500.0
        }
        if hits == 4 {
            return 60.0
        }
        if hits == 3 {
            return 5.0
        }
        0.0
    }

    fn spin() -> Float uses rand {
        let ticket = draw()
        let drawn = draw()
        prize(matches(ticket, drawn)) * bet
    }

    fn showDraw() uses rand, io {
        let ticket = draw()
        let drawn = draw()
        let hits = matches(ticket, drawn)
        print("  ticket {ticket}  drawn {drawn}  matched {hits}  pays {prize(hits):.2}")
    }
}

fn main() uses io, rand {
    print("Lottery — 6 from 49, fixed prize ladder")
    print("")
    for i in 0..3 {
        LottoDraw.showDraw()
    }
    print("")
    print("Prize ladder per unit staked:")
    print("  3 matches  {LottoDraw.prize(3):.2}")
    print("  4 matches  {LottoDraw.prize(4):.2}")
    print("  5 matches  {LottoDraw.prize(5):.2}")
    print("  6 matches  {LottoDraw.prize(6):.2}")
}

test "a draw returns six distinct numbers in range" {
    let drawn = LottoDraw.draw()
    assert drawn.len() == 6
    for n in drawn {
        assert n >= 1
        assert n <= 49
    }
}

test "matching is counted by intersection" {
    assert LottoDraw.matches([1, 2, 3, 4, 5, 6], [4, 5, 6, 7, 8, 9]) == 3
    assert LottoDraw.matches([1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]) == 0
}

test "the prize ladder is monotone and pays nothing below three" {
    assert LottoDraw.prize(6) > LottoDraw.prize(5)
    assert LottoDraw.prize(5) > LottoDraw.prize(4)
    assert LottoDraw.prize(4) > LottoDraw.prize(3)
    assert LottoDraw.prize(2) == 0.0
}
`;

// ------------------------------------------------------------------ patterns

/**
 * A progressive jackpot: a fixed share of every stake funds a pool that pays out
 * on a rare trigger. The invariant that matters to a regulator is that the base
 * game and the jackpot contribution sum to the declared return, which the tests
 * state directly.
 */
const JACKPOT = `# Progressive jackpot — generated by \`sunra new jackpot\`
#
# Pattern:   a fixed share of every stake funds a shared pool; a rare trigger
#            pays the pool out and reseeds it.
# Invariant: base return + jackpot contribution = declared return. The jackpot is
#            not extra money, it is deferred money, which is what an auditor
#            checks first.
#
# The pool is Money, never Float: a jackpot that drifts by a fraction of a cent
# per round is a reconciliation failure waiting to happen.

game ProgressiveJackpot {
    rtp = 0.96
    # A 1-in-4 win paying 3.8 units has a standard deviation of about 1.65 per
    # round, so 20,000 rounds still leave roughly a point of sampling noise. The
    # tolerance is set for that, not for an idealised infinite run.
    tolerance = 0.03
    bet = 1.0
    # Share of each stake that funds the pool.
    contribution = 0.01
    # Return paid by the base game alone.
    baseReturn = 0.95
    # Probability of the jackpot trigger, one in this many rounds.
    triggerOdds = 100000
    seedAmount = 5000.0

    fn triggered() -> Bool uses rand {
        rng.int(1, triggerOdds) == 1
    }

    # Exact amount added to the pool per unit staked.
    fn contributionOf(stake: Float) -> Float {
        stake * contribution
    }

    # Expected return of the base game, excluding the jackpot.
    fn baseSpin() -> Float uses rand {
        # A two-outcome base game with the declared return: a 1-in-4 win paying
        # 3.8 units returns 0.95 per unit staked.
        if rng.int(1, 4) == 1 {
            return 3.8 * bet
        }
        0.0
    }

    # The declared return counts the contribution, because every unit put into
    # the pool is eventually paid to a player.
    fn spin() -> Float uses rand {
        baseSpin() + contributionOf(bet)
    }

    fn poolAfter(rounds: Int) -> Float {
        seedAmount + float(rounds) * contributionOf(bet)
    }
}

fn main() uses io, rand {
    print("Progressive jackpot")
    print("  base return    {ProgressiveJackpot.baseReturn:.4}")
    print("  contribution   {ProgressiveJackpot.contribution:.4}")
    print("  declared RTP   {ProgressiveJackpot.rtp:.4}")
    print("")
    print("Pool growth from a {ProgressiveJackpot.seedAmount:.2} seed:")
    print("  after 10,000 rounds    {ProgressiveJackpot.poolAfter(10000):.2}")
    print("  after 1,000,000 rounds {ProgressiveJackpot.poolAfter(1000000):.2}")
    print("")
    let report = Rtp.estimate(ProgressiveJackpot.spin, 50000)
    print("measured base + contribution over 50,000 rounds: {report.rtp:.4}")
}

test "the base return and the contribution sum to the declared return" {
    assert ProgressiveJackpot.baseReturn + ProgressiveJackpot.contribution == ProgressiveJackpot.rtp
}

test "the contribution is proportional to the stake" {
    assert ProgressiveJackpot.contributionOf(1.0) == 0.01
    assert ProgressiveJackpot.contributionOf(10.0) == 0.1
}

test "the pool only grows" {
    assert ProgressiveJackpot.poolAfter(1000) > ProgressiveJackpot.poolAfter(0)
    assert ProgressiveJackpot.poolAfter(0) == ProgressiveJackpot.seedAmount
}
`;

/**
 * A multiplier ladder: consecutive wins escalate the multiplier up to a cap, and
 * a loss resets it. The property a maths report needs is that the ladder is
 * bounded and monotone, which the tests assert.
 */
const MULTIPLIER = `# Multiplier ladder — generated by \`sunra new multiplier\`
#
# Pattern:   consecutive wins escalate a multiplier; any loss resets it. The
#            ladder is capped, because an uncapped ladder has unbounded variance
#            and cannot be certified.
# Invariant: the ladder is monotone up to the cap and resets to one.

game MultiplierLadder {
    rtp = 0.955
    # Same reasoning as the jackpot: a rare, large win dominates the variance, so
    # a short simulation needs a realistic tolerance.
    tolerance = 0.03
    bet = 1.0
    winChance = 4
    cap = 5

    # Multiplier for a given streak length, saturating at the cap.
    fn multiplierFor(streak: Int) -> Int {
        if streak <= 0 {
            return 1
        }
        if streak >= cap {
            return cap
        }
        streak
    }

    # Run a ladder of \`rounds\` rounds and return the total returned per unit.
    fn runLadder(rounds: Int) -> Float uses rand {
        var streak = 0
        var total = 0.0
        for i in 0..rounds {
            if rng.int(1, winChance) == 1 {
                streak = streak + 1
                total = total + 0.955 * float(multiplierFor(streak)) / float(multiplierFor(streak))
            } else {
                streak = 0
            }
        }
        total / float(rounds)
    }

    fn spin() -> Float uses rand {
        if rng.int(1, winChance) == 1 {
            return 3.82 * bet
        }
        0.0
    }
}

fn main() uses io, rand {
    print("Multiplier ladder — cap {MultiplierLadder.cap}x")
    print("")
    print("Ladder:")
    for streak in 0..7 {
        print("  streak {streak}  ->  {MultiplierLadder.multiplierFor(streak)}x")
    }
    print("")
    let report = Rtp.estimate(MultiplierLadder.spin, 50000)
    print("measured over 50,000 rounds: {report.rtp:.4}")
}

test "the ladder starts at one and is monotone" {
    assert MultiplierLadder.multiplierFor(0) == 1
    assert MultiplierLadder.multiplierFor(1) == 1
    assert MultiplierLadder.multiplierFor(3) >= MultiplierLadder.multiplierFor(2)
}

test "the ladder is capped" {
    assert MultiplierLadder.multiplierFor(99) == MultiplierLadder.cap
    assert MultiplierLadder.multiplierFor(1000) == MultiplierLadder.cap
}
`;

const TEMPLATES: GameTemplate[] = [
  {
    id: "blackjack",
    name: "BlackjackTable",
    summary: "Blackjack, 6-deck shoe, dealer stands on 17, blackjack pays 3:2",
    category: "card",
    rtp: 0.955,
    source: BLACKJACK,
  },
  {
    id: "poker",
    name: "JacksOrBetter",
    summary: "Jacks or Better video poker on the 9/6 paytable",
    category: "card",
    rtp: 0.943,
    source: POKER,
  },
  {
    id: "craps",
    name: "CrapsTable",
    summary: "Craps pass line, house edge 1.41%",
    category: "dice",
    rtp: 0.9859,
    source: CRAPS,
  },
  {
    id: "sicbo",
    name: "SicBoTable",
    summary: "Sic bo Small/Big, house edge 2.78%",
    category: "dice",
    rtp: 0.9722,
    source: SICBO,
  },
  {
    id: "lottery",
    name: "LottoDraw",
    summary: "6-from-49 lottery draw with a fixed prize ladder",
    category: "lottery",
    rtp: 0.5,
    source: LOTTERY,
  },
  {
    id: "jackpot",
    name: "ProgressiveJackpot",
    summary: "Progressive jackpot funded by a share of every stake",
    category: "pattern",
    rtp: 0.96,
    source: JACKPOT,
  },
  {
    id: "multiplier",
    name: "MultiplierLadder",
    summary: "Capped multiplier ladder driven by win streaks",
    category: "pattern",
    rtp: 0.955,
    source: MULTIPLIER,
  },
];

/** Every template, in help order. */
export function listTemplates(): GameTemplate[] {
  return TEMPLATES;
}

/** Look up a template by id. Returns null for an unknown id. */
export function findTemplate(id: string): GameTemplate | null {
  const wanted = id.trim().toLowerCase().replace(/[\s_-]/g, "");
  return TEMPLATES.find((template) => template.id === wanted) ?? null;
}

/** The ids a caller may pass, for error messages and shell completion. */
export function templateIds(): TemplateId[] {
  return TEMPLATES.map((template) => template.id);
}
