/**
 * Cranelift backend.
 *
 * Cranelift is the fast-compile path: it trades peak code quality for
 * compilation speed, which is exactly the trade a developer wants on every
 * keystroke and a JIT wants at startup. This backend emits Cranelift IR text
 * (CLIF), the format `clif-util` and `cranelift-reader` consume.
 *
 * Differences from the LLVM backend that matter:
 *
 *   - CLIF blocks take *parameters* instead of phi instructions. A SunMIR phi
 *     therefore becomes a block parameter, and every jump to that block passes
 *     the corresponding value as an argument. This is the single largest
 *     structural difference and where a naive port would break.
 *   - Types are `i64`, `f64`, `i8` (bool) and `r64` (reference).
 *   - Calls need an explicit signature declaration in the function preamble.
 */
import type { Ty } from "../checker/checker.js";
import type { MirFunction, MirInstr, MirModule, ValueId, BlockId } from "../mir/mir.js";
import { llvmRuntimeBuiltin } from "./llvm.js";

export interface CraneliftOptions {
  /** `speed` favours a little optimisation; `speed_and_size` is the default. */
  optLevel?: "none" | "speed" | "speed_and_size";
  target?: "x86_64" | "aarch64";
  /** When true, emit a JIT-ready module preamble. */
  jit?: boolean;
}

export interface CraneliftOutput {
  clif: string;
  functions: string[];
  skipped: Array<{ symbol: string; reason: string }>;
  /** Signature declarations referenced by the emitted code. */
  imports: string[];
  jit: boolean;
}

const RUNTIME_SIGS: Array<{ name: string; sig: string }> = [
  { name: "sunra_list_new", sig: "(i64) -> r64" },
  { name: "sunra_list_set", sig: "(r64, i64, i64)" },
  { name: "sunra_list_get", sig: "(r64, i64) -> i64" },
  { name: "sunra_list_get_checked", sig: "(r64, i64) -> i64" },
  { name: "sunra_list_len", sig: "(r64) -> i64" },
  { name: "sunra_str_new", sig: "(r64, i64) -> r64" },
  { name: "sunra_str_concat", sig: "(r64, r64) -> r64" },
  { name: "sunra_release", sig: "(r64)" },
  { name: "sunra_arena_alloc", sig: "(i64) -> r64" },
  { name: "sunra_print_i64", sig: "(i64)" },
  { name: "sunra_print_f64", sig: "(f64)" },
  { name: "sunra_print_str", sig: "(r64)" },
];

/**
 * Builtin methods this backend lowers, sharing the LLVM backend's runtime ABI so
 * both native paths call the same helpers with the same signatures. Deriving the
 * CLIF signature from that one table is what keeps the two backends from drifting
 * apart as builtins are added.
 */
const BUILTIN_METHODS = [
  "len",
  "push",
  "pop",
  "contains",
  "indexOf",
  "slice",
  "concat",
  "reverse",
  "first",
  "last",
  "count",
  "join",
  "take",
  "sum",
  "upper",
  "lower",
  "trim",
  "split",
  "chars",
  "abs",
  "floor",
  "round",
  "sqrt",
  "min",
  "max",
  "assert",
];

/** CLIF signature text for a runtime builtin, e.g. `(r64, i64) -> r64`. */
function builtinSig(params: Ty[], ret: Ty): string {
  const args = params.map(clifType).join(", ");
  return ret.k === "Unit" ? `(${args})` : `(${args}) -> ${clifType(ret)}`;
}

/** Resolve a call to its runtime builtin, or null when it is a normal call. */
function builtinFor(
  instr: MirInstr & { op: "call" },
  fn: MirFunction,
): { symbol: string; params: Ty[]; ret: Ty } | null {
  if (instr.callee === "len") {
    return { symbol: "sunra_list_len", params: [{ k: "List", of: { k: "Unknown" } }], ret: { k: "Int" } };
  }
  if (!BUILTIN_METHODS.includes(instr.callee)) return null;
  const argTypes = instr.args.map((arg) => fn.types.get(arg) ?? ({ k: "Unknown" } as Ty));
  const runtime = llvmRuntimeBuiltin(instr.callee, argTypes);
  if (runtime === null) return null;
  return { symbol: runtime.symbol.replace(/^@/, ""), params: runtime.params, ret: runtime.ret };
}

export function emitCranelift(module: MirModule, options: CraneliftOptions = {}): CraneliftOutput {
  const jit = options.jit ?? false;
  const optLevel = options.optLevel ?? "speed_and_size";
  const target = options.target ?? "x86_64";
  const lines: string[] = [];
  const functions: string[] = [];
  const skipped: Array<{ symbol: string; reason: string }> = [];

  lines.push(`; Cranelift IR generated by the Sunra compiler`);
  lines.push(`target ${target === "x86_64" ? "x86_64" : "aarch64"}`);
  lines.push(`; opt_level = ${optLevel}${jit ? ", jit = true" : ""}`);
  lines.push("");

  const imports = RUNTIME_SIGS.map((s) => `    sig_${s.name} = ${s.sig}`);

  for (const fn of module.functions) {
    const result = emitFunction(fn, module);
    if (result.skipped) {
      skipped.push({ symbol: fn.symbol, reason: result.skipped });
      continue;
    }
    functions.push(fn.symbol);
    lines.push(result.text);
  }

  return { clif: lines.join("\n"), functions, skipped, imports, jit };
}

function emitFunction(fn: MirFunction, module: MirModule): { text: string; skipped?: string } {
  const out: string[] = [];
  // An unannotated parameter is Unknown in MIR, and Unknown maps to `i64`. That
  // is wrong for a list or string receiver, which is a reference. Recover the
  // real shape from how the body uses the value: a receiver of a reference-taking
  // builtin is `r64`.
  const paramTys = fn.params.map((p) => inferredParamTy(fn, p.value, p.ty));
  const params = fn.params.map((p, i) => `v${p.value}: ${clifType(paramTys[i])}`).join(", ");
  const ret = fn.ret.k === "Unit" ? "" : ` -> ${clifType(inferredRetTy(fn))}`;
  out.push(`function %${clifName(fn.symbol)}(${params})${ret} {`);

  // Collect phis per block: they become block parameters.
  const blockParams = new Map<BlockId, Array<{ value: ValueId; ty: Ty }>>();
  for (const block of fn.blocks) {
    const phis = block.instrs.filter((i) => i.op === "phi") as Array<MirInstr & { op: "phi" }>;
    if (phis.length > 0) {
      blockParams.set(
        block.id,
        phis.map((p) => ({ value: p.dst, ty: p.ty })),
      );
    }
  }

  // Signature declarations for the runtime calls this function performs.
  const used = new Set<string>();
  // Signatures for builtin helpers, which are not in RUNTIME_SIGS because their
  // shape depends on the operand types at the call site.
  const builtinSigs = new Map<string, string>();
  for (const block of fn.blocks) {
    for (const instr of block.instrs) {
      if (instr.op === "list") used.add("sunra_list_new");
      if (instr.op === "list") used.add("sunra_list_set");
      if (instr.op === "index") {
        // Which accessor is emitted depends on whether the optimiser elided the
        // bounds check, so declare the one the instruction will actually call.
        const checked = (instr as MirInstr & { op: "index"; checked?: boolean }).checked !== false;
        used.add(checked ? "sunra_list_get_checked" : "sunra_list_get");
      }
      if (instr.op === "drop") used.add("sunra_release");
      if (instr.op === "store" && instr.index !== null) used.add("sunra_list_set");
      if (instr.op === "arena") used.add("sunra_arena_alloc");
      // String `+` lowers to the runtime concatenation helper.
      if (instr.op === "binary" && instr.kind === "concat") used.add("sunra_str_concat");
      if (
        instr.op === "binary" &&
        instr.kind === "add" &&
        clifType(fn.types.get(instr.lhs) ?? ({ k: "Unknown" } as Ty)) === "r64"
      ) {
        used.add("sunra_str_concat");
      }
      if (instr.op === "call" && (instr.callee === "print" || instr.callee === "println")) {
        used.add("sunra_print_i64");
      }
      if (instr.op === "call") {
        const builtin = builtinFor(instr, fn);
        if (builtin !== null) {
          builtinSigs.set(builtin.symbol, builtinSig(builtin.params, builtin.ret));
        }
      }
      if (instr.op === "field") {
        builtinSigs.set(`sunra_field_${clifName(instr.name)}`, `(r64) -> ${clifType(instr.ty)}`);
      }
      if (instr.op === "store" && instr.index === null) {
        builtinSigs.set(
          `sunra_field_set_${clifName(instr.field ?? "value")}`,
          `(r64, ${clifType(fn.types.get(instr.value) ?? ({ k: "Unknown" } as Ty))})`,
        );
      }
    }
  }
  for (const name of [...used].sort()) {
    const sig = RUNTIME_SIGS.find((s) => s.name === name);
    if (sig) out.push(`    sig_${name} = ${sig.sig}`);
  }
  for (const name of [...builtinSigs.keys()].sort()) {
    out.push(`    sig_${name} = ${builtinSigs.get(name)}`);
  }
  for (const name of [...used].sort()) {
    out.push(`    fn_${name} = %${name} sig_${name}`);
  }
  for (const name of [...builtinSigs.keys()].sort()) {
    out.push(`    fn_${name} = %${name} sig_${name}`);
  }
  if (used.size > 0 || builtinSigs.size > 0) out.push("");

  for (const block of fn.blocks) {
    const paramList = blockParams.get(block.id);
    const header =
      paramList && paramList.length > 0
        ? `block${block.id}(${paramList.map((p) => `v${p.value}: ${clifType(p.ty)}`).join(", ")}):`
        : `block${block.id}:`;
    out.push(header);

    for (const instr of block.instrs) {
      // Phis are the block's parameters, so they emit nothing here.
      if (instr.op === "phi") continue;
      const text = emitInstr(instr, fn, module);
      if (text === null) return { text: "", skipped: `unsupported instruction: ${instr.op}` };
      if (text.length > 0) out.push(`    ${text}`);
    }

    out.push(`    ${emitTerminator(block.id, fn, blockParams)}`);
  }

  out.push("}");
  out.push("");
  return { text: out.join("\n") };
}

function emitInstr(instr: MirInstr, fn: MirFunction, module: MirModule): string | null {
  switch (instr.op) {
    case "const": {
      const value = instr.value;
      switch (value.k) {
        case "int":
          return `v${instr.dst} = iconst.i64 ${Math.trunc(value.value)}`;
        case "float":
          return `v${instr.dst} = f64const ${formatF64(value.value)}`;
        case "bool":
          return `v${instr.dst} = iconst.i8 ${value.value ? 1 : 0}`;
        case "str":
          // Strings live in a constant pool the runtime owns.
          return `v${instr.dst} = global_value.r64 gv_str_${hash(value.value)}`;
        case "unit":
          return `v${instr.dst} = iconst.i64 0`;
      }
      return null;
    }

    case "binary":
      return emitBinary(instr, fn);

    case "unary":
      if (instr.kind === "neg") {
        return instr.ty.k === "Float"
          ? `v${instr.dst} = fneg v${instr.operand}`
          : `v${instr.dst} = ineg v${instr.operand}`;
      }
      return `v${instr.dst} = bxor_imm v${instr.operand}, 1`;

    case "call": {
      if (instr.callee === "print" || instr.callee === "println") {
        const call = `call fn_sunra_print_i64(v${instr.args[0] ?? 0})`;
        return instr.dst === null ? call : `${call}\n    v${instr.dst} = iconst.i64 0`;
      }
      // Builtin methods go through the shared runtime ABI, with defaults supplied
      // for arguments the source omitted (`slice(start)` -> end = -1).
      const builtin = builtinFor(instr, fn);
      if (builtin !== null && instr.dst !== null) {
        const operands = builtin.params.map((paramTy, index) => {
          const arg = instr.args[index];
          return arg === undefined ? defaultOperand(paramTy, instr.dst!, index) : `v${arg}`;
        });
        const prelude = builtin.params
          .map((paramTy, index) =>
            instr.args[index] === undefined
              ? `${defaultOperand(paramTy, instr.dst!, index)} = ${defaultConst(paramTy)}`
              : null,
          )
          .filter((line): line is string => line !== null);
        const call =
          builtin.ret.k === "Unit"
            ? `call fn_${builtin.symbol}(${operands.join(", ")})`
            : `v${instr.dst} = call fn_${builtin.symbol}(${operands.join(", ")})`;
        return [...prelude, call].join("\n    ");
      }
      if (instr.callee.startsWith("intrinsic.load:")) {
        // A namespace handle or game-data read is an opaque reference at this
        // level; the runtime resolves it. Typed as the value's own type so the
        // CLIF stays well-typed.
        const ty = fn.types.get(instr.dst ?? -1) ?? instr.ty;
        return clifType(ty) === "r64"
          ? `v${instr.dst} = null.r64`
          : clifType(ty) === "f64"
            ? `v${instr.dst} = f64const 0.0`
            : `v${instr.dst} = iconst.${clifType(ty)} 0`;
      }
      const args = instr.args.map((a) => `v${a}`).join(", ");
      // Call the symbol that is actually defined in this module: MIR may record a
      // monomorphic name (`total$List_Int`) whose definition carries a different
      // mangling, and a call to an undefined symbol makes the CLIF unusable.
      const callee = resolveCallee(module, instr.callee);
      if (instr.dst === null || instr.ty.k === "Unit") {
        const call = `call %${clifName(callee)}(${args})`;
        return instr.dst === null ? call : `${call}\n    v${instr.dst} = iconst.i64 0`;
      }
      return `v${instr.dst} = call %${clifName(callee)}(${args})`;
    }

    case "list": {
      const arena = (instr as MirInstr & { op: "list"; arena?: boolean }).arena === true;
      const allocator = arena ? "fn_sunra_arena_alloc" : "fn_sunra_list_new";
      const lines = [
        `v${instr.dst} = call ${allocator}(v_len_${instr.dst})`,
        `; length ${instr.items.length}`,
      ];
      // Cranelift needs the length as a value, so materialise it inline.
      lines.unshift(`v_len_${instr.dst} = iconst.i64 ${instr.items.length}`);
      instr.items.forEach((item, index) => {
        lines.push(`v_idx_${instr.dst}_${index} = iconst.i64 ${index}`);
        lines.push(
          `call fn_sunra_list_set(v${instr.dst}, v_idx_${instr.dst}_${index}, v${item})`,
        );
      });
      return lines.join("\n    ");
    }

    case "index": {
      const checked = (instr as MirInstr & { op: "index"; checked?: boolean }).checked !== false;
      const callee = checked ? "fn_sunra_list_get_checked" : "fn_sunra_list_get";
      return `v${instr.dst} = call ${callee}(v${instr.object}, v${instr.index})`;
    }

    case "field":
      return `v${instr.dst} = call fn_sunra_field_${clifName(instr.name)}(v${instr.object})`;

    case "store":
      if (instr.index !== null) {
        return `call fn_sunra_list_set(v${instr.object}, v${instr.index}, v${instr.value})`;
      }
      return `call fn_sunra_field_set_${clifName(instr.field ?? "value")}(v${instr.object}, v${instr.value})`;

    case "drop":
      return `call fn_sunra_release(v${instr.value})`;

    case "arena":
      return `v${instr.dst} = call fn_sunra_arena_alloc(v${instr.source})`;

    case "phi":
      return "";
  }
}

function emitBinary(instr: MirInstr & { op: "binary" }, fn: MirFunction): string {
  const operandTy = fn.types.get(instr.lhs) ?? instr.ty;
  const isFloat = operandTy.k === "Float" || instr.ty.k === "Float";

  const arith: Record<string, [string, string]> = {
    add: ["iadd", "fadd"],
    sub: ["isub", "fsub"],
    mul: ["imul", "fmul"],
    div: ["sdiv", "fdiv"],
    rem: ["srem", "fdiv"],
  };
  if (instr.kind in arith) {
    const [intOp, floatOp] = arith[instr.kind];
    return `v${instr.dst} = ${isFloat ? floatOp : intOp} v${instr.lhs}, v${instr.rhs}`;
  }

  const cmp: Record<string, string> = {
    eq: "eq",
    ne: "ne",
    lt: isFloat ? "lt" : "slt",
    le: isFloat ? "le" : "sle",
    gt: isFloat ? "gt" : "sgt",
    ge: isFloat ? "ge" : "sge",
  };
  if (instr.kind in cmp) {
    return isFloat
      ? `v${instr.dst} = fcmp ${cmp[instr.kind]} v${instr.lhs}, v${instr.rhs}`
      : `v${instr.dst} = icmp ${cmp[instr.kind]} v${instr.lhs}, v${instr.rhs}`;
  }

  if (instr.kind === "and") return `v${instr.dst} = band v${instr.lhs}, v${instr.rhs}`;
  if (instr.kind === "or") return `v${instr.dst} = bor v${instr.lhs}, v${instr.rhs}`;
  if (instr.kind === "concat") {
    return `v${instr.dst} = call fn_sunra_str_concat(v${instr.lhs}, v${instr.rhs})`;
  }
  return `; unsupported binary ${instr.kind}`;
}

/**
 * Terminators must pass block arguments for the target's phi parameters, which
 * is how CLIF expresses what SunMIR writes as a phi.
 */
function emitTerminator(
  blockId: BlockId,
  fn: MirFunction,
  blockParams: Map<BlockId, Array<{ value: ValueId; ty: Ty }>>,
): string {
  const block = fn.blocks.find((b) => b.id === blockId)!;
  const term = block.terminator;

  const argsFor = (target: BlockId): string => {
    const params = blockParams.get(target);
    if (!params || params.length === 0) return "";
    const targetBlock = fn.blocks.find((b) => b.id === target);
    const phis = (targetBlock?.instrs.filter((i) => i.op === "phi") ?? []) as Array<
      MirInstr & { op: "phi" }
    >;
    const values = phis.map((phi) => {
      const source = phi.sources.find((s) => s.block === blockId);
      // A missing source means this edge was added after the phi; passing the
      // first source keeps the IR well-formed rather than emitting a dangling arg.
      return `v${source ? source.value : phi.sources[0]?.value ?? 0}`;
    });
    return `(${values.join(", ")})`;
  };

  switch (term.op) {
    case "jump":
      return `jump block${term.target}${argsFor(term.target)}`;
    case "branch":
      return `brif v${term.cond}, block${term.then}${argsFor(term.then)}, block${term.otherwise}${argsFor(term.otherwise)}`;
    case "return":
      return term.value === null || fn.ret.k === "Unit" ? "return" : `return v${term.value}`;
    case "unreachable":
      return "trap user0";
  }
}

export function clifType(ty: Ty): string {
  switch (ty.k) {
    case "Int":
    case "Money":
    case "Unknown":
      return "i64";
    case "Float":
      return "f64";
    case "Bool":
      return "i8";
    case "Unit":
      return "i64";
    case "Str":
    case "List":
    case "Named":
    case "Fn":
      return "r64";
  }
}

function clifName(symbol: string): string {
  return symbol.replace(/[^A-Za-z0-9_]/g, "_");
}

/**
 * Map a callee to a symbol this module defines.
 *
 * Exact match first, then the same base name with any monomorphic suffix, then
 * the source-level name. Falls back to the original so an external call still
 * emits something meaningful.
 */
function resolveCallee(module: MirModule, callee: string): string {
  if (module.functions.some((fn) => fn.symbol === callee)) return callee;
  const base = callee.split("$")[0];
  const byBase = module.functions.find((fn) => fn.symbol.split("$")[0] === base);
  if (byBase) return byBase.symbol;
  const byName = module.functions.find((fn) => fn.name === base);
  return byName ? byName.symbol : callee;
}

/**
 * Backend type of a parameter whose source type is unknown.
 *
 * Evidence, in order: a builtin that takes the value as a reference receiver, use
 * as the object of an index/field/store, or use in float arithmetic.
 */
function inferredParamTy(fn: MirFunction, value: ValueId, declared: Ty): Ty {
  if (declared.k !== "Unknown") return declared;
  for (const block of fn.blocks) {
    for (const instr of block.instrs) {
      if (instr.op === "call") {
        const builtin = builtinFor(instr, fn);
        if (builtin !== null) {
          const index = instr.args.indexOf(value);
          if (index >= 0) {
            const paramTy = builtin.params[index];
            if (paramTy && paramTy.k !== "Unknown") return paramTy;
            if (paramTy) return { k: "List", of: { k: "Unknown" } };
          }
        }
      }
      if (instr.op === "index" && instr.object === value) return { k: "List", of: instr.ty };
      if (instr.op === "field" && instr.object === value) return { k: "Named", name: "Object" } as Ty;
      if (instr.op === "store" && instr.object === value) return { k: "List", of: { k: "Unknown" } };
      if (instr.op === "binary" && (instr.lhs === value || instr.rhs === value) && instr.ty.k === "Float") {
        return { k: "Float" };
      }
    }
  }
  return declared;
}

/** Backend return type, recovered from the returned value when undeclared. */
function inferredRetTy(fn: MirFunction): Ty {
  if (fn.ret.k !== "Unknown") return fn.ret;
  for (const block of fn.blocks) {
    if (block.terminator.op !== "return" || block.terminator.value === null) continue;
    const ty = fn.types.get(block.terminator.value);
    if (ty && ty.k !== "Unknown") return ty;
  }
  return fn.ret;
}

/** Name of the synthetic value holding a default builtin argument. */
function defaultOperand(ty: Ty, dst: ValueId, index: number): string {
  return `v_def_${dst}_${index}`;
}

/** CLIF constant for an omitted builtin argument. */
function defaultConst(ty: Ty): string {
  const clif = clifType(ty);
  if (clif === "r64") return "null.r64";
  if (clif === "f64") return "f64const 0.0";
  // `slice(start)` with no end means "to the end of the receiver"; -1 is the
  // runtime's sentinel for that, matching the LLVM backend.
  return `iconst.${clif} -1`;
}

function formatF64(value: number): string {
  return Number.isInteger(value) ? `0x${value.toString(16)}.0p0` : String(value);
}

function hash(value: string): string {
  let h = 2166136261;
  for (let i = 0; i < value.length; i++) {
    h ^= value.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return (h >>> 0).toString(16);
}
